namespace grocery_store.GUI
{
    partial class Main
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Main));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.panel_UC = new System.Windows.Forms.Panel();
            this.panel_header = new Bunifu.UI.WinForms.BunifuPanel();
            this.btn_minimize = new Bunifu.UI.WinForms.BunifuImageButton();
            this.btn_close = new Bunifu.UI.WinForms.BunifuImageButton();
            this.panel_control = new Bunifu.UI.WinForms.BunifuPanel();
            this.Copyright = new System.Windows.Forms.Label();
            this.logo_Code = new System.Windows.Forms.PictureBox();
            this.btn_logout = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btn_manage = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btn_staff = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btn_statistical = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btn_good = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btn_invoice = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btn_sell = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.Logo = new System.Windows.Forms.PictureBox();
            this.panel_UC.SuspendLayout();
            this.panel_header.SuspendLayout();
            this.panel_control.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.logo_Code)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.Logo)).BeginInit();
            this.SuspendLayout();
            // 
            // panel_UC
            // 
            this.panel_UC.Location = new System.Drawing.Point(300, 30);
            this.panel_UC.Name = "panel_UC";
            this.panel_UC.Size = new System.Drawing.Size(1620, 1050);
            this.panel_UC.TabIndex = 2;
            // 
            // panel_header
            // 
            this.panel_header.BackgroundColor = System.Drawing.SystemColors.ActiveBorder;
            this.panel_header.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("panel_header.BackgroundImage")));
            this.panel_header.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.panel_header.BorderColor = System.Drawing.Color.Transparent;
            this.panel_header.BorderRadius = 0;
            this.panel_header.BorderThickness = 0;
            this.panel_header.Controls.Add(this.btn_minimize);
            this.panel_header.Controls.Add(this.btn_close);
            this.panel_header.Location = new System.Drawing.Point(300, 0);
            this.panel_header.Margin = new System.Windows.Forms.Padding(0);
            this.panel_header.Name = "panel_header";
            this.panel_header.ShowBorders = false;
            this.panel_header.Size = new System.Drawing.Size(1620, 30);
            this.panel_header.TabIndex = 1;
            // 
            // btn_minimize
            // 
            this.btn_minimize.ActiveImage = null;
            this.btn_minimize.AllowAnimations = true;
            this.btn_minimize.AllowBuffering = false;
            this.btn_minimize.AllowToggling = false;
            this.btn_minimize.AllowZooming = true;
            this.btn_minimize.AllowZoomingOnFocus = false;
            this.btn_minimize.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(241)))), ((int)(((byte)(235)))), ((int)(((byte)(144)))));
            this.btn_minimize.BackgroundImageLayout = System.Windows.Forms.ImageLayout.None;
            this.btn_minimize.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_minimize.ErrorImage = ((System.Drawing.Image)(resources.GetObject("btn_minimize.ErrorImage")));
            this.btn_minimize.FadeWhenInactive = false;
            this.btn_minimize.Flip = Bunifu.UI.WinForms.BunifuImageButton.FlipOrientation.Normal;
            this.btn_minimize.ForeColor = System.Drawing.Color.Transparent;
            this.btn_minimize.Image = ((System.Drawing.Image)(resources.GetObject("btn_minimize.Image")));
            this.btn_minimize.ImageActive = null;
            this.btn_minimize.ImageLocation = null;
            this.btn_minimize.ImageMargin = 0;
            this.btn_minimize.ImageSize = new System.Drawing.Size(29, 29);
            this.btn_minimize.ImageZoomSize = new System.Drawing.Size(30, 30);
            this.btn_minimize.InitialImage = ((System.Drawing.Image)(resources.GetObject("btn_minimize.InitialImage")));
            this.btn_minimize.Location = new System.Drawing.Point(1558, 0);
            this.btn_minimize.Margin = new System.Windows.Forms.Padding(0);
            this.btn_minimize.Name = "btn_minimize";
            this.btn_minimize.Rotation = 0;
            this.btn_minimize.ShowActiveImage = true;
            this.btn_minimize.ShowCursorChanges = true;
            this.btn_minimize.ShowImageBorders = false;
            this.btn_minimize.ShowSizeMarkers = false;
            this.btn_minimize.Size = new System.Drawing.Size(30, 30);
            this.btn_minimize.TabIndex = 3;
            this.btn_minimize.ToolTipText = "";
            this.btn_minimize.WaitOnLoad = false;
            this.btn_minimize.Zoom = 0;
            this.btn_minimize.ZoomSpeed = 10;
            this.btn_minimize.Click += new System.EventHandler(this.btn_minimize_Click);
            // 
            // btn_close
            // 
            this.btn_close.ActiveImage = null;
            this.btn_close.AllowAnimations = true;
            this.btn_close.AllowBuffering = false;
            this.btn_close.AllowToggling = false;
            this.btn_close.AllowZooming = true;
            this.btn_close.AllowZoomingOnFocus = false;
            this.btn_close.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.btn_close.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(49)))), ((int)(((byte)(49)))));
            this.btn_close.BackgroundImageLayout = System.Windows.Forms.ImageLayout.None;
            this.btn_close.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_close.ErrorImage = ((System.Drawing.Image)(resources.GetObject("btn_close.ErrorImage")));
            this.btn_close.FadeWhenInactive = false;
            this.btn_close.Flip = Bunifu.UI.WinForms.BunifuImageButton.FlipOrientation.Normal;
            this.btn_close.ForeColor = System.Drawing.Color.Transparent;
            this.btn_close.Image = global::grocery_store.Properties.Resources.close_bold_svgrepo_com;
            this.btn_close.ImageActive = null;
            this.btn_close.ImageLocation = null;
            this.btn_close.ImageMargin = 0;
            this.btn_close.ImageSize = new System.Drawing.Size(31, 29);
            this.btn_close.ImageZoomSize = new System.Drawing.Size(32, 30);
            this.btn_close.InitialImage = ((System.Drawing.Image)(resources.GetObject("btn_close.InitialImage")));
            this.btn_close.Location = new System.Drawing.Point(1588, 0);
            this.btn_close.Margin = new System.Windows.Forms.Padding(0);
            this.btn_close.Name = "btn_close";
            this.btn_close.Rotation = 0;
            this.btn_close.ShowActiveImage = true;
            this.btn_close.ShowCursorChanges = true;
            this.btn_close.ShowImageBorders = false;
            this.btn_close.ShowSizeMarkers = false;
            this.btn_close.Size = new System.Drawing.Size(32, 30);
            this.btn_close.TabIndex = 2;
            this.btn_close.ToolTipText = "";
            this.btn_close.WaitOnLoad = false;
            this.btn_close.Zoom = 0;
            this.btn_close.ZoomSpeed = 10;
            this.btn_close.Click += new System.EventHandler(this.btn_close_Click);
            // 
            // panel_control
            // 
            this.panel_control.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink;
            this.panel_control.BackgroundColor = System.Drawing.Color.White;
            this.panel_control.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("panel_control.BackgroundImage")));
            this.panel_control.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.panel_control.BorderColor = System.Drawing.Color.Transparent;
            this.panel_control.BorderRadius = 0;
            this.panel_control.BorderThickness = 0;
            this.panel_control.Controls.Add(this.Copyright);
            this.panel_control.Controls.Add(this.logo_Code);
            this.panel_control.Controls.Add(this.btn_logout);
            this.panel_control.Controls.Add(this.btn_manage);
            this.panel_control.Controls.Add(this.btn_staff);
            this.panel_control.Controls.Add(this.btn_statistical);
            this.panel_control.Controls.Add(this.btn_good);
            this.panel_control.Controls.Add(this.btn_invoice);
            this.panel_control.Controls.Add(this.btn_sell);
            this.panel_control.Controls.Add(this.Logo);
            this.panel_control.Location = new System.Drawing.Point(0, 0);
            this.panel_control.Margin = new System.Windows.Forms.Padding(0);
            this.panel_control.Name = "panel_control";
            this.panel_control.ShowBorders = false;
            this.panel_control.Size = new System.Drawing.Size(300, 1080);
            this.panel_control.TabIndex = 0;
            // 
            // Copyright
            // 
            this.Copyright.AutoSize = true;
            this.Copyright.BackColor = System.Drawing.Color.Transparent;
            this.Copyright.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.Copyright.Location = new System.Drawing.Point(96, 1028);
            this.Copyright.Name = "Copyright";
            this.Copyright.Size = new System.Drawing.Size(162, 18);
            this.Copyright.TabIndex = 11;
            this.Copyright.Text = "Develop by Vượt cạn";
            // 
            // logo_Code
            // 
            this.logo_Code.BackColor = System.Drawing.Color.Transparent;
            this.logo_Code.BackgroundImageLayout = System.Windows.Forms.ImageLayout.None;
            this.logo_Code.Image = global::grocery_store.Properties.Resources.code__2_;
            this.logo_Code.Location = new System.Drawing.Point(52, 1013);
            this.logo_Code.Name = "logo_Code";
            this.logo_Code.Size = new System.Drawing.Size(38, 50);
            this.logo_Code.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.logo_Code.TabIndex = 10;
            this.logo_Code.TabStop = false;
            // 
            // btn_logout
            // 
            this.btn_logout.AllowAnimations = true;
            this.btn_logout.AllowMouseEffects = true;
            this.btn_logout.AllowToggling = true;
            this.btn_logout.AnimationSpeed = 5;
            this.btn_logout.AutoGenerateColors = false;
            this.btn_logout.AutoRoundBorders = false;
            this.btn_logout.AutoSizeLeftIcon = true;
            this.btn_logout.AutoSizeRightIcon = true;
            this.btn_logout.BackColor = System.Drawing.Color.Transparent;
            this.btn_logout.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(186)))), ((int)(((byte)(163)))));
            this.btn_logout.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_logout.BackgroundImage")));
            this.btn_logout.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_logout.ButtonText = "Thoát";
            this.btn_logout.ButtonTextMarginLeft = 0;
            this.btn_logout.ColorContrastOnClick = 45;
            this.btn_logout.ColorContrastOnHover = 45;
            this.btn_logout.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btn_logout.CustomizableEdges = borderEdges1;
            this.btn_logout.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_logout.DisabledBorderColor = System.Drawing.Color.Black;
            this.btn_logout.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(186)))), ((int)(((byte)(163)))));
            this.btn_logout.DisabledForecolor = System.Drawing.Color.Black;
            this.btn_logout.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btn_logout.Font = new System.Drawing.Font("Segoe UI", 18F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.btn_logout.ForeColor = System.Drawing.Color.Black;
            this.btn_logout.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_logout.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn_logout.IconLeftPadding = new System.Windows.Forms.Padding(20, 3, 3, 3);
            this.btn_logout.IconMarginLeft = 11;
            this.btn_logout.IconPadding = 10;
            this.btn_logout.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_logout.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn_logout.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn_logout.IconSize = 25;
            this.btn_logout.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btn_logout.IdleBorderRadius = 30;
            this.btn_logout.IdleBorderThickness = 1;
            this.btn_logout.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(186)))), ((int)(((byte)(163)))));
            this.btn_logout.IdleIconLeftImage = global::grocery_store.Properties.Resources.logout;
            this.btn_logout.IdleIconRightImage = null;
            this.btn_logout.IndicateFocus = true;
            this.btn_logout.Location = new System.Drawing.Point(12, 938);
            this.btn_logout.Name = "btn_logout";
            this.btn_logout.OnDisabledState.BorderColor = System.Drawing.Color.Black;
            this.btn_logout.OnDisabledState.BorderRadius = 30;
            this.btn_logout.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_logout.OnDisabledState.BorderThickness = 1;
            this.btn_logout.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(186)))), ((int)(((byte)(163)))));
            this.btn_logout.OnDisabledState.ForeColor = System.Drawing.Color.Black;
            this.btn_logout.OnDisabledState.IconLeftImage = null;
            this.btn_logout.OnDisabledState.IconRightImage = null;
            this.btn_logout.onHoverState.BorderColor = System.Drawing.Color.Transparent;
            this.btn_logout.onHoverState.BorderRadius = 30;
            this.btn_logout.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_logout.onHoverState.BorderThickness = 1;
            this.btn_logout.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(69)))), ((int)(((byte)(69)))));
            this.btn_logout.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.btn_logout.onHoverState.IconLeftImage = null;
            this.btn_logout.onHoverState.IconRightImage = null;
            this.btn_logout.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btn_logout.OnIdleState.BorderRadius = 30;
            this.btn_logout.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_logout.OnIdleState.BorderThickness = 1;
            this.btn_logout.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(186)))), ((int)(((byte)(163)))));
            this.btn_logout.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.btn_logout.OnIdleState.IconLeftImage = global::grocery_store.Properties.Resources.logout;
            this.btn_logout.OnIdleState.IconRightImage = null;
            this.btn_logout.OnPressedState.BorderColor = System.Drawing.Color.Transparent;
            this.btn_logout.OnPressedState.BorderRadius = 30;
            this.btn_logout.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_logout.OnPressedState.BorderThickness = 1;
            this.btn_logout.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(169)))), ((int)(((byte)(68)))), ((int)(((byte)(56)))));
            this.btn_logout.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.btn_logout.OnPressedState.IconLeftImage = null;
            this.btn_logout.OnPressedState.IconRightImage = null;
            this.btn_logout.Size = new System.Drawing.Size(275, 70);
            this.btn_logout.TabIndex = 8;
            this.btn_logout.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_logout.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_logout.TextMarginLeft = 0;
            this.btn_logout.TextPadding = new System.Windows.Forms.Padding(20, 0, 0, 0);
            this.btn_logout.UseDefaultRadiusAndThickness = true;
            this.btn_logout.Click += new System.EventHandler(this.btn_logout_Click);
            // 
            // btn_manage
            // 
            this.btn_manage.AllowAnimations = true;
            this.btn_manage.AllowMouseEffects = true;
            this.btn_manage.AllowToggling = true;
            this.btn_manage.AnimationSpeed = 5;
            this.btn_manage.AutoGenerateColors = false;
            this.btn_manage.AutoRoundBorders = false;
            this.btn_manage.AutoSizeLeftIcon = true;
            this.btn_manage.AutoSizeRightIcon = true;
            this.btn_manage.BackColor = System.Drawing.Color.Transparent;
            this.btn_manage.BackColor1 = System.Drawing.Color.White;
            this.btn_manage.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_manage.BackgroundImage")));
            this.btn_manage.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_manage.ButtonText = "Quản lý";
            this.btn_manage.ButtonTextMarginLeft = 0;
            this.btn_manage.ColorContrastOnClick = 45;
            this.btn_manage.ColorContrastOnHover = 45;
            this.btn_manage.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btn_manage.CustomizableEdges = borderEdges2;
            this.btn_manage.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_manage.DisabledBorderColor = System.Drawing.Color.Black;
            this.btn_manage.DisabledFillColor = System.Drawing.Color.White;
            this.btn_manage.DisabledForecolor = System.Drawing.Color.Transparent;
            this.btn_manage.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btn_manage.Font = new System.Drawing.Font("Segoe UI", 18F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.btn_manage.ForeColor = System.Drawing.Color.Black;
            this.btn_manage.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_manage.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn_manage.IconLeftPadding = new System.Windows.Forms.Padding(20, 3, 3, 3);
            this.btn_manage.IconMarginLeft = 11;
            this.btn_manage.IconPadding = 10;
            this.btn_manage.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_manage.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn_manage.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn_manage.IconSize = 25;
            this.btn_manage.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btn_manage.IdleBorderRadius = 30;
            this.btn_manage.IdleBorderThickness = 1;
            this.btn_manage.IdleFillColor = System.Drawing.Color.White;
            this.btn_manage.IdleIconLeftImage = global::grocery_store.Properties.Resources.shield;
            this.btn_manage.IdleIconRightImage = null;
            this.btn_manage.IndicateFocus = true;
            this.btn_manage.Location = new System.Drawing.Point(12, 600);
            this.btn_manage.Margin = new System.Windows.Forms.Padding(3, 3, 3, 0);
            this.btn_manage.Name = "btn_manage";
            this.btn_manage.OnDisabledState.BorderColor = System.Drawing.Color.Black;
            this.btn_manage.OnDisabledState.BorderRadius = 30;
            this.btn_manage.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_manage.OnDisabledState.BorderThickness = 1;
            this.btn_manage.OnDisabledState.FillColor = System.Drawing.Color.White;
            this.btn_manage.OnDisabledState.ForeColor = System.Drawing.Color.Transparent;
            this.btn_manage.OnDisabledState.IconLeftImage = null;
            this.btn_manage.OnDisabledState.IconRightImage = null;
            this.btn_manage.onHoverState.BorderColor = System.Drawing.Color.Transparent;
            this.btn_manage.onHoverState.BorderRadius = 30;
            this.btn_manage.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_manage.onHoverState.BorderThickness = 1;
            this.btn_manage.onHoverState.FillColor = System.Drawing.SystemColors.ScrollBar;
            this.btn_manage.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.btn_manage.onHoverState.IconLeftImage = null;
            this.btn_manage.onHoverState.IconRightImage = null;
            this.btn_manage.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btn_manage.OnIdleState.BorderRadius = 30;
            this.btn_manage.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_manage.OnIdleState.BorderThickness = 1;
            this.btn_manage.OnIdleState.FillColor = System.Drawing.Color.White;
            this.btn_manage.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.btn_manage.OnIdleState.IconLeftImage = global::grocery_store.Properties.Resources.shield;
            this.btn_manage.OnIdleState.IconRightImage = null;
            this.btn_manage.OnPressedState.BorderColor = System.Drawing.Color.Transparent;
            this.btn_manage.OnPressedState.BorderRadius = 30;
            this.btn_manage.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_manage.OnPressedState.BorderThickness = 1;
            this.btn_manage.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(162)))), ((int)(((byte)(129)))));
            this.btn_manage.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.btn_manage.OnPressedState.IconLeftImage = null;
            this.btn_manage.OnPressedState.IconRightImage = null;
            this.btn_manage.Size = new System.Drawing.Size(275, 70);
            this.btn_manage.TabIndex = 7;
            this.btn_manage.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_manage.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_manage.TextMarginLeft = 0;
            this.btn_manage.TextPadding = new System.Windows.Forms.Padding(20, 0, 0, 0);
            this.btn_manage.UseDefaultRadiusAndThickness = true;
            this.btn_manage.Click += new System.EventHandler(this.btn_manage_Click);
            // 
            // btn_staff
            // 
            this.btn_staff.AllowAnimations = true;
            this.btn_staff.AllowMouseEffects = true;
            this.btn_staff.AllowToggling = true;
            this.btn_staff.AnimationSpeed = 5;
            this.btn_staff.AutoGenerateColors = false;
            this.btn_staff.AutoRoundBorders = false;
            this.btn_staff.AutoSizeLeftIcon = true;
            this.btn_staff.AutoSizeRightIcon = true;
            this.btn_staff.BackColor = System.Drawing.Color.Transparent;
            this.btn_staff.BackColor1 = System.Drawing.Color.White;
            this.btn_staff.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_staff.BackgroundImage")));
            this.btn_staff.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_staff.ButtonText = "Nhân viên";
            this.btn_staff.ButtonTextMarginLeft = 0;
            this.btn_staff.ColorContrastOnClick = 45;
            this.btn_staff.ColorContrastOnHover = 45;
            this.btn_staff.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btn_staff.CustomizableEdges = borderEdges3;
            this.btn_staff.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_staff.DisabledBorderColor = System.Drawing.Color.Black;
            this.btn_staff.DisabledFillColor = System.Drawing.Color.White;
            this.btn_staff.DisabledForecolor = System.Drawing.Color.Black;
            this.btn_staff.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btn_staff.Font = new System.Drawing.Font("Segoe UI", 18F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.btn_staff.ForeColor = System.Drawing.Color.Black;
            this.btn_staff.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_staff.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn_staff.IconLeftPadding = new System.Windows.Forms.Padding(20, 3, 3, 3);
            this.btn_staff.IconMarginLeft = 11;
            this.btn_staff.IconPadding = 10;
            this.btn_staff.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_staff.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn_staff.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn_staff.IconSize = 25;
            this.btn_staff.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btn_staff.IdleBorderRadius = 30;
            this.btn_staff.IdleBorderThickness = 1;
            this.btn_staff.IdleFillColor = System.Drawing.Color.White;
            this.btn_staff.IdleIconLeftImage = global::grocery_store.Properties.Resources.user;
            this.btn_staff.IdleIconRightImage = null;
            this.btn_staff.IndicateFocus = true;
            this.btn_staff.Location = new System.Drawing.Point(12, 530);
            this.btn_staff.Margin = new System.Windows.Forms.Padding(3, 3, 3, 0);
            this.btn_staff.Name = "btn_staff";
            this.btn_staff.OnDisabledState.BorderColor = System.Drawing.Color.Black;
            this.btn_staff.OnDisabledState.BorderRadius = 30;
            this.btn_staff.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_staff.OnDisabledState.BorderThickness = 1;
            this.btn_staff.OnDisabledState.FillColor = System.Drawing.Color.White;
            this.btn_staff.OnDisabledState.ForeColor = System.Drawing.Color.Black;
            this.btn_staff.OnDisabledState.IconLeftImage = null;
            this.btn_staff.OnDisabledState.IconRightImage = null;
            this.btn_staff.onHoverState.BorderColor = System.Drawing.Color.Transparent;
            this.btn_staff.onHoverState.BorderRadius = 30;
            this.btn_staff.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_staff.onHoverState.BorderThickness = 1;
            this.btn_staff.onHoverState.FillColor = System.Drawing.SystemColors.ScrollBar;
            this.btn_staff.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.btn_staff.onHoverState.IconLeftImage = null;
            this.btn_staff.onHoverState.IconRightImage = null;
            this.btn_staff.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btn_staff.OnIdleState.BorderRadius = 30;
            this.btn_staff.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_staff.OnIdleState.BorderThickness = 1;
            this.btn_staff.OnIdleState.FillColor = System.Drawing.Color.White;
            this.btn_staff.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.btn_staff.OnIdleState.IconLeftImage = global::grocery_store.Properties.Resources.user;
            this.btn_staff.OnIdleState.IconRightImage = null;
            this.btn_staff.OnPressedState.BorderColor = System.Drawing.Color.Transparent;
            this.btn_staff.OnPressedState.BorderRadius = 30;
            this.btn_staff.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_staff.OnPressedState.BorderThickness = 1;
            this.btn_staff.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(162)))), ((int)(((byte)(129)))));
            this.btn_staff.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.btn_staff.OnPressedState.IconLeftImage = null;
            this.btn_staff.OnPressedState.IconRightImage = null;
            this.btn_staff.Size = new System.Drawing.Size(275, 70);
            this.btn_staff.TabIndex = 6;
            this.btn_staff.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_staff.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_staff.TextMarginLeft = 0;
            this.btn_staff.TextPadding = new System.Windows.Forms.Padding(20, 0, 0, 0);
            this.btn_staff.UseDefaultRadiusAndThickness = true;
            this.btn_staff.Click += new System.EventHandler(this.btn_staff_Click);
            // 
            // btn_statistical
            // 
            this.btn_statistical.AllowAnimations = true;
            this.btn_statistical.AllowMouseEffects = true;
            this.btn_statistical.AllowToggling = true;
            this.btn_statistical.AnimationSpeed = 5;
            this.btn_statistical.AutoGenerateColors = false;
            this.btn_statistical.AutoRoundBorders = false;
            this.btn_statistical.AutoSizeLeftIcon = true;
            this.btn_statistical.AutoSizeRightIcon = true;
            this.btn_statistical.BackColor = System.Drawing.Color.Transparent;
            this.btn_statistical.BackColor1 = System.Drawing.Color.White;
            this.btn_statistical.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_statistical.BackgroundImage")));
            this.btn_statistical.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_statistical.ButtonText = "Thống kê";
            this.btn_statistical.ButtonTextMarginLeft = 0;
            this.btn_statistical.ColorContrastOnClick = 45;
            this.btn_statistical.ColorContrastOnHover = 45;
            this.btn_statistical.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.btn_statistical.CustomizableEdges = borderEdges4;
            this.btn_statistical.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_statistical.DisabledBorderColor = System.Drawing.Color.Black;
            this.btn_statistical.DisabledFillColor = System.Drawing.Color.White;
            this.btn_statistical.DisabledForecolor = System.Drawing.Color.Black;
            this.btn_statistical.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btn_statistical.Font = new System.Drawing.Font("Segoe UI", 18F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.btn_statistical.ForeColor = System.Drawing.Color.Black;
            this.btn_statistical.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_statistical.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn_statistical.IconLeftPadding = new System.Windows.Forms.Padding(20, 3, 3, 3);
            this.btn_statistical.IconMarginLeft = 11;
            this.btn_statistical.IconPadding = 10;
            this.btn_statistical.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_statistical.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn_statistical.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn_statistical.IconSize = 25;
            this.btn_statistical.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btn_statistical.IdleBorderRadius = 30;
            this.btn_statistical.IdleBorderThickness = 1;
            this.btn_statistical.IdleFillColor = System.Drawing.Color.White;
            this.btn_statistical.IdleIconLeftImage = global::grocery_store.Properties.Resources.chart;
            this.btn_statistical.IdleIconRightImage = null;
            this.btn_statistical.IndicateFocus = true;
            this.btn_statistical.Location = new System.Drawing.Point(12, 460);
            this.btn_statistical.Margin = new System.Windows.Forms.Padding(3, 3, 3, 0);
            this.btn_statistical.Name = "btn_statistical";
            this.btn_statistical.OnDisabledState.BorderColor = System.Drawing.Color.Black;
            this.btn_statistical.OnDisabledState.BorderRadius = 30;
            this.btn_statistical.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_statistical.OnDisabledState.BorderThickness = 1;
            this.btn_statistical.OnDisabledState.FillColor = System.Drawing.Color.White;
            this.btn_statistical.OnDisabledState.ForeColor = System.Drawing.Color.Black;
            this.btn_statistical.OnDisabledState.IconLeftImage = null;
            this.btn_statistical.OnDisabledState.IconRightImage = null;
            this.btn_statistical.onHoverState.BorderColor = System.Drawing.Color.Transparent;
            this.btn_statistical.onHoverState.BorderRadius = 30;
            this.btn_statistical.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_statistical.onHoverState.BorderThickness = 1;
            this.btn_statistical.onHoverState.FillColor = System.Drawing.SystemColors.ScrollBar;
            this.btn_statistical.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.btn_statistical.onHoverState.IconLeftImage = null;
            this.btn_statistical.onHoverState.IconRightImage = null;
            this.btn_statistical.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btn_statistical.OnIdleState.BorderRadius = 30;
            this.btn_statistical.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_statistical.OnIdleState.BorderThickness = 1;
            this.btn_statistical.OnIdleState.FillColor = System.Drawing.Color.White;
            this.btn_statistical.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.btn_statistical.OnIdleState.IconLeftImage = global::grocery_store.Properties.Resources.chart;
            this.btn_statistical.OnIdleState.IconRightImage = null;
            this.btn_statistical.OnPressedState.BorderColor = System.Drawing.Color.Transparent;
            this.btn_statistical.OnPressedState.BorderRadius = 30;
            this.btn_statistical.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_statistical.OnPressedState.BorderThickness = 1;
            this.btn_statistical.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(162)))), ((int)(((byte)(129)))));
            this.btn_statistical.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.btn_statistical.OnPressedState.IconLeftImage = null;
            this.btn_statistical.OnPressedState.IconRightImage = null;
            this.btn_statistical.Size = new System.Drawing.Size(275, 70);
            this.btn_statistical.TabIndex = 5;
            this.btn_statistical.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_statistical.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_statistical.TextMarginLeft = 0;
            this.btn_statistical.TextPadding = new System.Windows.Forms.Padding(20, 0, 0, 0);
            this.btn_statistical.UseDefaultRadiusAndThickness = true;
            this.btn_statistical.Click += new System.EventHandler(this.btn_statistical_Click);
            // 
            // btn_good
            // 
            this.btn_good.AllowAnimations = true;
            this.btn_good.AllowMouseEffects = true;
            this.btn_good.AllowToggling = true;
            this.btn_good.AnimationSpeed = 5;
            this.btn_good.AutoGenerateColors = false;
            this.btn_good.AutoRoundBorders = false;
            this.btn_good.AutoSizeLeftIcon = true;
            this.btn_good.AutoSizeRightIcon = true;
            this.btn_good.BackColor = System.Drawing.Color.Transparent;
            this.btn_good.BackColor1 = System.Drawing.Color.White;
            this.btn_good.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_good.BackgroundImage")));
            this.btn_good.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_good.ButtonText = "Hàng hoá";
            this.btn_good.ButtonTextMarginLeft = 0;
            this.btn_good.ColorContrastOnClick = 45;
            this.btn_good.ColorContrastOnHover = 45;
            this.btn_good.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.btn_good.CustomizableEdges = borderEdges5;
            this.btn_good.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_good.DisabledBorderColor = System.Drawing.Color.Black;
            this.btn_good.DisabledFillColor = System.Drawing.Color.White;
            this.btn_good.DisabledForecolor = System.Drawing.Color.Black;
            this.btn_good.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btn_good.Font = new System.Drawing.Font("Segoe UI", 18F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.btn_good.ForeColor = System.Drawing.Color.Black;
            this.btn_good.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_good.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn_good.IconLeftPadding = new System.Windows.Forms.Padding(20, 3, 3, 3);
            this.btn_good.IconMarginLeft = 11;
            this.btn_good.IconPadding = 10;
            this.btn_good.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_good.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn_good.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn_good.IconSize = 25;
            this.btn_good.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btn_good.IdleBorderRadius = 30;
            this.btn_good.IdleBorderThickness = 1;
            this.btn_good.IdleFillColor = System.Drawing.Color.White;
            this.btn_good.IdleIconLeftImage = global::grocery_store.Properties.Resources.box;
            this.btn_good.IdleIconRightImage = null;
            this.btn_good.IndicateFocus = true;
            this.btn_good.Location = new System.Drawing.Point(12, 390);
            this.btn_good.Margin = new System.Windows.Forms.Padding(3, 3, 3, 0);
            this.btn_good.Name = "btn_good";
            this.btn_good.OnDisabledState.BorderColor = System.Drawing.Color.Black;
            this.btn_good.OnDisabledState.BorderRadius = 30;
            this.btn_good.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_good.OnDisabledState.BorderThickness = 1;
            this.btn_good.OnDisabledState.FillColor = System.Drawing.Color.White;
            this.btn_good.OnDisabledState.ForeColor = System.Drawing.Color.Black;
            this.btn_good.OnDisabledState.IconLeftImage = null;
            this.btn_good.OnDisabledState.IconRightImage = null;
            this.btn_good.onHoverState.BorderColor = System.Drawing.Color.Transparent;
            this.btn_good.onHoverState.BorderRadius = 30;
            this.btn_good.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_good.onHoverState.BorderThickness = 1;
            this.btn_good.onHoverState.FillColor = System.Drawing.SystemColors.ScrollBar;
            this.btn_good.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.btn_good.onHoverState.IconLeftImage = null;
            this.btn_good.onHoverState.IconRightImage = null;
            this.btn_good.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btn_good.OnIdleState.BorderRadius = 30;
            this.btn_good.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_good.OnIdleState.BorderThickness = 1;
            this.btn_good.OnIdleState.FillColor = System.Drawing.Color.White;
            this.btn_good.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.btn_good.OnIdleState.IconLeftImage = global::grocery_store.Properties.Resources.box;
            this.btn_good.OnIdleState.IconRightImage = null;
            this.btn_good.OnPressedState.BorderColor = System.Drawing.Color.Transparent;
            this.btn_good.OnPressedState.BorderRadius = 30;
            this.btn_good.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_good.OnPressedState.BorderThickness = 1;
            this.btn_good.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(162)))), ((int)(((byte)(129)))));
            this.btn_good.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.btn_good.OnPressedState.IconLeftImage = null;
            this.btn_good.OnPressedState.IconRightImage = null;
            this.btn_good.Size = new System.Drawing.Size(275, 70);
            this.btn_good.TabIndex = 4;
            this.btn_good.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_good.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_good.TextMarginLeft = 0;
            this.btn_good.TextPadding = new System.Windows.Forms.Padding(20, 0, 0, 0);
            this.btn_good.UseDefaultRadiusAndThickness = true;
            this.btn_good.Click += new System.EventHandler(this.btn_good_Click);
            // 
            // btn_invoice
            // 
            this.btn_invoice.AllowAnimations = true;
            this.btn_invoice.AllowMouseEffects = true;
            this.btn_invoice.AllowToggling = true;
            this.btn_invoice.AnimationSpeed = 5;
            this.btn_invoice.AutoGenerateColors = false;
            this.btn_invoice.AutoRoundBorders = false;
            this.btn_invoice.AutoSizeLeftIcon = true;
            this.btn_invoice.AutoSizeRightIcon = true;
            this.btn_invoice.BackColor = System.Drawing.Color.Transparent;
            this.btn_invoice.BackColor1 = System.Drawing.Color.White;
            this.btn_invoice.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_invoice.BackgroundImage")));
            this.btn_invoice.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_invoice.ButtonText = "Hoá đơn";
            this.btn_invoice.ButtonTextMarginLeft = 0;
            this.btn_invoice.ColorContrastOnClick = 45;
            this.btn_invoice.ColorContrastOnHover = 45;
            this.btn_invoice.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.btn_invoice.CustomizableEdges = borderEdges6;
            this.btn_invoice.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_invoice.DisabledBorderColor = System.Drawing.Color.Black;
            this.btn_invoice.DisabledFillColor = System.Drawing.Color.White;
            this.btn_invoice.DisabledForecolor = System.Drawing.Color.Black;
            this.btn_invoice.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btn_invoice.Font = new System.Drawing.Font("Segoe UI", 18F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.btn_invoice.ForeColor = System.Drawing.Color.Black;
            this.btn_invoice.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_invoice.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn_invoice.IconLeftPadding = new System.Windows.Forms.Padding(20, 3, 3, 3);
            this.btn_invoice.IconMarginLeft = 11;
            this.btn_invoice.IconPadding = 10;
            this.btn_invoice.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_invoice.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn_invoice.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn_invoice.IconSize = 25;
            this.btn_invoice.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btn_invoice.IdleBorderRadius = 30;
            this.btn_invoice.IdleBorderThickness = 1;
            this.btn_invoice.IdleFillColor = System.Drawing.Color.White;
            this.btn_invoice.IdleIconLeftImage = global::grocery_store.Properties.Resources.bill_list;
            this.btn_invoice.IdleIconRightImage = null;
            this.btn_invoice.IndicateFocus = true;
            this.btn_invoice.Location = new System.Drawing.Point(12, 320);
            this.btn_invoice.Margin = new System.Windows.Forms.Padding(3, 3, 3, 0);
            this.btn_invoice.Name = "btn_invoice";
            this.btn_invoice.OnDisabledState.BorderColor = System.Drawing.Color.Black;
            this.btn_invoice.OnDisabledState.BorderRadius = 30;
            this.btn_invoice.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_invoice.OnDisabledState.BorderThickness = 1;
            this.btn_invoice.OnDisabledState.FillColor = System.Drawing.Color.White;
            this.btn_invoice.OnDisabledState.ForeColor = System.Drawing.Color.Black;
            this.btn_invoice.OnDisabledState.IconLeftImage = null;
            this.btn_invoice.OnDisabledState.IconRightImage = null;
            this.btn_invoice.onHoverState.BorderColor = System.Drawing.Color.Transparent;
            this.btn_invoice.onHoverState.BorderRadius = 30;
            this.btn_invoice.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_invoice.onHoverState.BorderThickness = 1;
            this.btn_invoice.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(221)))), ((int)(((byte)(221)))));
            this.btn_invoice.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.btn_invoice.onHoverState.IconLeftImage = null;
            this.btn_invoice.onHoverState.IconRightImage = null;
            this.btn_invoice.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btn_invoice.OnIdleState.BorderRadius = 30;
            this.btn_invoice.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_invoice.OnIdleState.BorderThickness = 1;
            this.btn_invoice.OnIdleState.FillColor = System.Drawing.Color.White;
            this.btn_invoice.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.btn_invoice.OnIdleState.IconLeftImage = global::grocery_store.Properties.Resources.bill_list;
            this.btn_invoice.OnIdleState.IconRightImage = null;
            this.btn_invoice.OnPressedState.BorderColor = System.Drawing.Color.Transparent;
            this.btn_invoice.OnPressedState.BorderRadius = 30;
            this.btn_invoice.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_invoice.OnPressedState.BorderThickness = 1;
            this.btn_invoice.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(162)))), ((int)(((byte)(129)))));
            this.btn_invoice.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.btn_invoice.OnPressedState.IconLeftImage = null;
            this.btn_invoice.OnPressedState.IconRightImage = null;
            this.btn_invoice.Size = new System.Drawing.Size(275, 70);
            this.btn_invoice.TabIndex = 3;
            this.btn_invoice.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_invoice.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_invoice.TextMarginLeft = 0;
            this.btn_invoice.TextPadding = new System.Windows.Forms.Padding(20, 0, 0, 0);
            this.btn_invoice.UseDefaultRadiusAndThickness = true;
            this.btn_invoice.Click += new System.EventHandler(this.btn_invoice_Click);
            // 
            // btn_sell
            // 
            this.btn_sell.AllowAnimations = true;
            this.btn_sell.AllowMouseEffects = true;
            this.btn_sell.AllowToggling = true;
            this.btn_sell.AnimationSpeed = 5;
            this.btn_sell.AutoGenerateColors = false;
            this.btn_sell.AutoRoundBorders = false;
            this.btn_sell.AutoSizeLeftIcon = true;
            this.btn_sell.AutoSizeRightIcon = true;
            this.btn_sell.BackColor = System.Drawing.Color.Transparent;
            this.btn_sell.BackColor1 = System.Drawing.Color.White;
            this.btn_sell.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_sell.BackgroundImage")));
            this.btn_sell.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_sell.ButtonText = "Bán hàng";
            this.btn_sell.ButtonTextMarginLeft = 0;
            this.btn_sell.ColorContrastOnClick = 45;
            this.btn_sell.ColorContrastOnHover = 45;
            this.btn_sell.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.btn_sell.CustomizableEdges = borderEdges7;
            this.btn_sell.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_sell.DisabledBorderColor = System.Drawing.Color.Black;
            this.btn_sell.DisabledFillColor = System.Drawing.Color.White;
            this.btn_sell.DisabledForecolor = System.Drawing.Color.Transparent;
            this.btn_sell.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btn_sell.Font = new System.Drawing.Font("Segoe UI", 18F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.btn_sell.ForeColor = System.Drawing.Color.Black;
            this.btn_sell.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_sell.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn_sell.IconLeftPadding = new System.Windows.Forms.Padding(20, 3, 3, 3);
            this.btn_sell.IconMarginLeft = 11;
            this.btn_sell.IconPadding = 10;
            this.btn_sell.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_sell.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn_sell.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn_sell.IconSize = 25;
            this.btn_sell.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btn_sell.IdleBorderRadius = 30;
            this.btn_sell.IdleBorderThickness = 1;
            this.btn_sell.IdleFillColor = System.Drawing.Color.White;
            this.btn_sell.IdleIconLeftImage = global::grocery_store.Properties.Resources.cart;
            this.btn_sell.IdleIconRightImage = null;
            this.btn_sell.IndicateFocus = true;
            this.btn_sell.Location = new System.Drawing.Point(12, 250);
            this.btn_sell.Margin = new System.Windows.Forms.Padding(3, 3, 3, 0);
            this.btn_sell.Name = "btn_sell";
            this.btn_sell.OnDisabledState.BorderColor = System.Drawing.Color.Black;
            this.btn_sell.OnDisabledState.BorderRadius = 30;
            this.btn_sell.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_sell.OnDisabledState.BorderThickness = 1;
            this.btn_sell.OnDisabledState.FillColor = System.Drawing.Color.White;
            this.btn_sell.OnDisabledState.ForeColor = System.Drawing.Color.Transparent;
            this.btn_sell.OnDisabledState.IconLeftImage = null;
            this.btn_sell.OnDisabledState.IconRightImage = null;
            this.btn_sell.onHoverState.BorderColor = System.Drawing.Color.Transparent;
            this.btn_sell.onHoverState.BorderRadius = 30;
            this.btn_sell.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_sell.onHoverState.BorderThickness = 1;
            this.btn_sell.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(221)))), ((int)(((byte)(221)))));
            this.btn_sell.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.btn_sell.onHoverState.IconLeftImage = null;
            this.btn_sell.onHoverState.IconRightImage = null;
            this.btn_sell.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btn_sell.OnIdleState.BorderRadius = 30;
            this.btn_sell.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_sell.OnIdleState.BorderThickness = 1;
            this.btn_sell.OnIdleState.FillColor = System.Drawing.Color.White;
            this.btn_sell.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.btn_sell.OnIdleState.IconLeftImage = global::grocery_store.Properties.Resources.cart;
            this.btn_sell.OnIdleState.IconRightImage = null;
            this.btn_sell.OnPressedState.BorderColor = System.Drawing.Color.Transparent;
            this.btn_sell.OnPressedState.BorderRadius = 30;
            this.btn_sell.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_sell.OnPressedState.BorderThickness = 1;
            this.btn_sell.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(162)))), ((int)(((byte)(129)))));
            this.btn_sell.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.btn_sell.OnPressedState.IconLeftImage = null;
            this.btn_sell.OnPressedState.IconRightImage = null;
            this.btn_sell.Size = new System.Drawing.Size(275, 70);
            this.btn_sell.TabIndex = 2;
            this.btn_sell.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_sell.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_sell.TextMarginLeft = 0;
            this.btn_sell.TextPadding = new System.Windows.Forms.Padding(20, 0, 0, 0);
            this.btn_sell.UseDefaultRadiusAndThickness = true;
            this.btn_sell.Click += new System.EventHandler(this.btn_sell_Click);
            // 
            // Logo
            // 
            this.Logo.BackColor = System.Drawing.Color.Transparent;
            this.Logo.BackgroundImageLayout = System.Windows.Forms.ImageLayout.None;
            this.Logo.Image = global::grocery_store.Properties.Resources.takeeasy;
            this.Logo.Location = new System.Drawing.Point(61, 55);
            this.Logo.Margin = new System.Windows.Forms.Padding(0);
            this.Logo.Name = "Logo";
            this.Logo.Size = new System.Drawing.Size(168, 138);
            this.Logo.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.Logo.TabIndex = 1;
            this.Logo.TabStop = false;
            // 
            // Main
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(120F, 120F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Dpi;
            this.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(254)))), ((int)(((byte)(250)))), ((int)(((byte)(224)))));
            this.ClientSize = new System.Drawing.Size(1920, 1080);
            this.ControlBox = false;
            this.Controls.Add(this.panel_UC);
            this.Controls.Add(this.panel_header);
            this.Controls.Add(this.panel_control);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.Name = "Main";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Takeasy";
            this.WindowState = System.Windows.Forms.FormWindowState.Maximized;
            this.Load += new System.EventHandler(this.Main_Load);
            this.panel_UC.ResumeLayout(false);
            this.panel_header.ResumeLayout(false);
            this.panel_control.ResumeLayout(false);
            this.panel_control.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.logo_Code)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.Logo)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuPanel panel_control;
        private Bunifu.UI.WinForms.BunifuPanel panel_header;
        private Bunifu.UI.WinForms.BunifuImageButton btn_close;
        private Bunifu.UI.WinForms.BunifuImageButton btn_minimize;
        private System.Windows.Forms.PictureBox Logo;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_sell;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_invoice;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_good;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_statistical;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_logout;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_manage;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_staff;
        private System.Windows.Forms.PictureBox logo_Code;
        private System.Windows.Forms.Label Copyright;
        private System.Windows.Forms.Panel panel_UC;

    }
}